toolbar:
  -  styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent 
plugins:
  - advlist 


content_css:
    - '//www.tinymce.com/css/codepen.min.css'

